input {
  beats {
    port => 5044
  }
}

filter {
  if [latencyNanos] {
    mutate {
      convert => {
        "latencyNanos" => "integer"
      }
    }
    ruby {
      code => "event.set('latencyMs', event.get('latencyNanos').to_f / 1000000.0)"
    }
  }

  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }

  mutate {
    add_field => {
      "[event][dataset]" => "netsentinel.audit"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "netsentinel-audit-%{+YYYY.MM.dd}"
  }
}
